---
- include_tasks: 
    file: check_vars.yml
    apply:
      tags:
        - ferm
        - check
  tags:
    - always

- include_tasks:
    file: ferm.yml
    apply:
      tags:
        - ferm
  tags:
    - always
